### ISSUE TITLE
hosts

### ISSUE THREAD

**Issue by ghost** [tosdr/phoenix#1154]
I could distribute a list of sites that I consider important and trustworthy and those that are not. For example, the computer file hosts is an operating system file that maps hostnames to IP addresses. It is a plain text file. Originally a file named HOSTS.TXT was manually maintained and made available via file sharing by Stanford Research Institute for the ARPANET membership, containing the hostname. Would it be interesting to offer a version of edit.tosdr for the "host" file?

**Comment by Deveroonie** [comment]
Hey!

ToS;DR do distribute a hosts file blocking any website with an E grade. It can be found at https://api.tosdr.org/pihole/

**Comment by Deveroonie** [comment]
> Hi @Deveroonie, thanks for info here

You're welcome!

**Comment by Deveroonie** [comment]
> Hi @Deveroonie 
> 
> > You're welcome!
> 
> Want to hear an interesting idea?

Sure!
