### ISSUE TITLE
Ordering functionalities

### ISSUE THREAD

**Issue by HumanG33k** [tosdr/phoenix#167]
Can you add an order by good practices function. (main page)
Can you add an order by "color" on the website page. (like https://phoenix.tosdr.org/services/6 )

**Comment by piks3l** [comment]
Hey ! Thanks for your feedback :)

So, what do you suggest is : 
* ordering functionalities for the main page
* on service page improving the display of the point with colors ?

**Comment by HumanG33k** [comment]
ordering functionalities for the main page :
it can be done but i thought more about a rank ordering : 

Duck Duck go first,
Facebook, Skype at the end.

on service page improving the display of the point with colors ? :
For service page allow to display : 
1st green point 
2 nd green point 
[...]
1 grey point 
[...]
1 red point 
[...]
or the opposite
