### ISSUE TITLE
Add some free software pod

### ISSUE THREAD

**Issue by HumanG33k** [tosdr/phoenix#170]
Add some diaspora, mastodon instances in order to permit to user to choice their services.
Ask to chaton to do it.

Maybe an ai can be train to auto fill a template with all information ?
A taxonomy have be done  with all kind of "features" can be find in TOS ?

**Comment by piks3l** [comment]
> Add some diaspora, mastodon instances in order to permit to user to choice their services.
> Ask to chaton to do it.

I'm very confused, what do you want with mastodon or diaspora instances ? Chatons already provide a wide range of services, plus do the promotion of those. Phoenix is not designed to do the same job as Framasoft. We rate web-services' ToS, that's it.

> Maybe an ai can be train to auto fill a template with all information ?

A template of what ? All ToS are pretty different and if an AI does it, it'll surely break or return false information. We value user-based input (points) as a token of understanding and contribution.

If you're interested into scraping and see if ToS changes, maybe take a look at our other project: (ToSBack)[https://github.com/tosdr/tosback2]

>  A taxonomy have be done with all kind of "features" can be find in TOS ?

Features of Phoenix ? A small one can be found on the wiki but need to be expanded. I'll do that in the coming days.

Please for the future issues, make clear of what you want, speak about etc. You can speak in French as well if that's easier for you 😄

**Comment by HumanG33k** [comment]
Donc ce que je propose :
C’est au même titre que duck duck go ajouter les contrats des différentes instances de chatons.
Je trouve que c’est trés bien d’avoir les informations des grand groupe mais on le sait déja que c’est mal, rajouter les alernatives serait bien et permettrait de sortir de cet état d’esprit "de toute facon il n’y a pas d’alternative". 

Quand je parle de template je parle de faire une cartographie complete de ce que l’on peut trouver dans les TOS. Je n’ai pas checké le comment les données sont insérées  mais cela pourrait permettre d’accélérer l’import de nouveau site.

Je suis du genre a vouloir automatiser le plus possible :)

**Comment by piks3l** [comment]
> C’est au même titre que duck duck go ajouter les contrats des différentes instances de chatons.

On va mettre en place une manière pour demander l'analyse d'un service :)

> Quand je parle de template je parle de faire une cartographie complete de ce que l’on peut trouver 
> dans les TOS. Je n’ai pas checké le comment les données sont insérées mais cela pourrait 
> permettre d’accélérer l’import de nouveau site.

T'es loin d'être le.a seul.e a proposer ça ! :D Malheureusement, c'est plus compliqué que ça et une AI ne pourra jamais saisir des subtilités en fonction de leur context lexical et de leur service. Si on arrive à faire une AI comme ça, on aurait plus besoin d'avocats x)

On a essayé de rendre les formulaires les plus simples possibles, on pourrait encore bosser sur l'UX ou bien sur l'add-on FF/Chrome pour envoyer un point directement depuis cette interface, mais c'est le maximum qu'on peut faire (et ça ne concerne pas Phoenix pour la 2e proposition).

**Comment by HumanG33k** [comment]
Hum une ia d’analyse de texte de loi a été mise en prod dans un tribunal en bretagne je crois. (oui, je pars vite dans plein d’idées.) Il faudrait faire un mapping fonctionnel exhaustif.

De la facon dont je vois les choses : 
Il faut séparer le coté demande d’analyse et analyse a proprement parlé.
un addon Firefox ou tu clic sur un bouton et cela envoi une demande pour le site en cours.
Si a l’installation un id est généré et envoyé a l’api alors cela peut en plus mettre en avant lesquels sont le plus prioritaire.

Coté analyse, une liste trié, avec un tool collaboratif, si les ToS sont lu par un humain alors on  peut imaginer 1 couleur pour surligner ce qu‘a lu un compte. 

Enfin c’est des idées.

**Comment by piks3l** [comment]
> Hum une ia d’analyse de texte de loi a été mise en prod dans un tribunal en bretagne je crois. (oui, je 
> pars vite dans plein d’idées.) Il faudrait faire un mapping fonctionnel exhaustif.

Justement, je crois que c'est aussi assez critiqué... Mais je n'ai pas regardé de plus près.

> De la facon dont je vois les choses :

Pour le coup, ça a l'air assez cool comme idée. Par contre, il faut des outils qui fonctionnent et sont interopérables. C'est pas encore le cas, donc une chose à la fois :)

**Comment by hugoroy** [comment]
↪ piks3l / novembre 28, 2017 22:44:
>> Hum une ia d’analyse de texte de loi a été mise en prod dans un tribunal en bretagne je crois. (oui, je 
>> pars vite dans plein d’idées.) Il faudrait faire un mapping fonctionnel exhaustif.
> 
> Justement, je crois que c'est aussi assez critiqué... Mais je n'ai pas regardé de plus près.

Oui, mais c'est un logiciel qui ne fait qu'analyser des tous petits
bouts de décisions et qui est limité à regarder les montants des
condamnations.

Bref, rien de très utile pour ToS;DR.

Le NLP (natural language processing) nous en entendons parler depuis des
années à ToS;DR de la part d'étudiants et d'entreprises qui s'y
intéressent.

Pour l'instant, on ne m'a jamais rien montré d'utilisable :^)

**Comment by piks3l** [comment]
No more activity here, closing.
