### ISSUE TITLE
Allow contributors to add services

### ISSUE THREAD

**Issue by babolivier** [tosdr/phoenix#172]
It'd be a great thing if contributors could add services to review, so they aren't limited to predefined services when want to add a point. I don't know if this is already a work in progress, though.

**Comment by piks3l** [comment]
Hey ! Thanks for your feedback :)

It was in discussion for the alpha. But as we are still trying to work on the import of the old database, we prefer not to mangle too much with the current one. Also, we wanted to keep a certain control of services not too end up with too much empty ratings. Indeed, a new service will appear directly on the front page, but not a point as it needs to be curated (moderated). I hope this makes sense to you.

Nonetheless, what will come is a possibility for contributors to request new services. 

I hope this answers your question 😄

**Comment by babolivier** [comment]
It totally answers my question, thanks! 😃
