### ISSUE TITLE
initialize database

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#180]
https://github.com/tosdr/phoenix/blob/master/config/database.yml#L84-L85 specifies that a 'phoenix' postgres user should exist, it should have a password, and the 'phoenix_development' or 'phoenix_production' database should be created.

**Comment by michielbdejong** [comment]
The postgres on my laptop is a bit messy, so trying this out on heroku now.

**Comment by piks3l** [comment]
@michielbdejong if you need help with anything, just hit me up on irc :)

**Comment by michielbdejong** [comment]
heroku run rake db:seed

**Comment by michielbdejong** [comment]
This is now documented in https://github.com/tosdr/phoenix/blob/master/CONTRIBUTING.md#when-its-done
