### ISSUE TITLE
redis?

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#181]
https://github.com/tosdr/phoenix/blob/master/config/cable.yml mentions redis, is that stale code, or is redis being used alongside postgres?

**Comment by piks3l** [comment]
It is used to manage Cache, Session, HTTP Cache in production, it is automatically added when installing an empty rails project. More at the docs : https://github.com/redis-store/redis-rails

**Comment by michielbdejong** [comment]
ok, thanks for clarifying!
