### ISSUE TITLE
rethink tagline

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#184]
"The Internet's fine print, written for humans, not lawyers." -> how about "read by humans"? we don't write ToS or summaries thereof, we just read and rate. The goal is not that a user of our website understands what the original text contains, but that they can learn about the community's opinion about that original text is. There will obviously be quotes and as you read a ToS;DR review, you also get a bit of a summary of the actual ToS text, but summarizing is not the goal, reviewing is the goal.

**Comment by piks3l** [comment]
Or we could go with the original one (which is also pretty long). We needed a new tagline for the exercise of inventing a new tagline, but there are no problems with taking the previous one :)

**Comment by michielbdejong** [comment]
:)

**Comment by michielbdejong** [comment]
Done in #190
