### ISSUE TITLE
Think about how we handle the data change log

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#193]
Until now, data was in json files in a github repo, and so version control was awesome. By moving to a live-displayed database, we inevitably give some of that up. What we *do* have:

* the postgres logs; I take it backups and replication work roughly the same way as in mysql, so we can recreate the exact history of the database query-by-query by replaying the binlog. Question: how do we back those up? Export to .sql and commit to git? It would contain both queries done by rails (db:create db:migrate db:seed etc) and queries that were a result of button clicks, but if you were to import them, then you would get the exact db state that rails understands, so that would not be so bad maybe.
* the comments; I'm adding comments like "imported from ..." to points. i could make these more machine-readable maybe that's a bad and superfluous concept, as it sort of duplicates the binlog, but not quite.

**Comment by michielbdejong** [comment]
I guess maybe the best option is to commit the db logs into git (maybe a separate git repo). That also then gives us a workable architecture for running a mirror of the production instance, which could be useful for all kinds of reasons.

**Comment by michielbdejong** [comment]
and maybe add an 'action log' table that attempts to make the binlogs more annotated and readable.

**Comment by piks3l** [comment]
I see many ways we could use a version control for the db. We have an api, maybe we could look up from that side ? I don't think that sending .sql to github is a viable solution :/

**Comment by michielbdejong** [comment]
It's not so much about how we give people access to this log data, more about how do we track it in the first place (if at all). Especially if there are bugs in the code, there is a risk that work gets lost if people have worked on editing points.

**Comment by michielbdejong** [comment]
https://github.com/airblade/paper_trail looks useful! Maybe I'll try that out.

**Comment by piks3l** [comment]
Implemented with good (enough) ux
