### ISSUE TITLE
Delete a service ? Purpose of such an option

### ISSUE THREAD

**Issue by Natouille** [tosdr/phoenix#216]
Why is there the opportinity to delete a service ?

**Comment by piks3l** [comment]
So, it's true when you tested the service could be deleted. Although, as I expected, we thought of this when developing the first version of the alpha and it is impossible to delete a service if there are points attached to it. 

> controllers/services_controller.rb :
```
def destroy
    if @service.points.any?
      flash[:alert] = "Users have contributed valuable insight to this service!"
      redirect_to service_path(@service)
    else
      @service.destroy
      flash[:notice] = "Service has been removed!"
      redirect_to services_path
    end
  end
```

Nonetheless, I'll keep this option in cases there are services added with and there should be a reason for deleting it. To be honest, not having this option feels, to me, like it will be missing. 

So if no one have any comment on this, I'll be closing this issue.

**Comment by Natouille** [comment]
Well, it could be an option for admins only

**Comment by piks3l** [comment]
Well, even thought curators see this option, they cannot do it unless they remove all points linked to the said service.

**Comment by piks3l** [comment]
Curators are already a special statuses, they are like moderators
