### ISSUE TITLE
[bug][v0.2.3-alpha] error 500 after sigin 

### ISSUE THREAD

**Issue by piks3l** [tosdr/phoenix#218]
The error is created by the method `deactivated?` in `user.rb` which is a new implementation in v0.2.3. The issue didn't appear in local but in production. Currently working the issue out.

**Comment by hugoroy** [comment]
FWIW, it dind't happen to me when testing

**Comment by michielbdejong** [comment]
This must have been fixed since then - if not, please reopen.
