### ISSUE TITLE
Stronger Password Policy

### ISSUE THREAD

**Issue by hugoroy** [tosdr/phoenix#227]
Right now passwords are '6 characters minimum'

We should find more secure ways for authentication (including maybe getting rid of passwords and using other authentication mecanisms such as email links).

To start, the rules on passwords should be stronger; eg.

- minimum 8 or 10 characters
- not allowing passwords which are only lower case letters
- not allowing passwords which are only numerals

**Comment by piks3l** [comment]
See #257

**Comment by piks3l** [comment]
> not allowing passwords which are only lower case letters
> not allowing passwords which are only numerals

Wait doesn't that mean that we can read the password ? Otherwise it's a JS on the client page that checks the password input and it seems to me to be a security issue (wild guess). Otherwise, the length of the password is ready to be merged in #257
