### ISSUE TITLE
Divergent views on a service if logged in 

### ISSUE THREAD

**Issue by hugoroy** [tosdr/phoenix#228]
When not-logged in, this is the view for a service (eg Facebook):

![image](https://user-images.githubusercontent.com/1629771/34623846-2adaee46-f253-11e7-9c71-f577d6582d6f.png)

When logged in, this is the view for the same service:

![image](https://user-images.githubusercontent.com/1629771/34623858-36243dac-f253-11e7-9748-dece58ce3e14.png)

I think it would be best to avoid to have completely divergent UI for this.

Especially, the descriptions of each point should be visible.

**Comment by hugoroy** [comment]
In my opinion, these are the important views:

- create a completely new point 
- create a completely new service / edit the technical info on a service
- home page
- display/edit a service's list of points (should be based on the same view but show more actions when loggedin)
- display/edit/discuss a point (should be based on the same view but show more actions when loggedin)
- moderate / vote on points  (should be based on the same view but show more actions when loggedin as moderator)
- user settings

I think "topics" are important but we should deal with this later :-)

**Comment by piks3l** [comment]
Will be fixed in #253

**Comment by piks3l** [comment]
> display/edit/discuss a point (should be based on the same view but show more actions when loggedin)

We decided not to have a discussion board right now for moderation issues. I'm open to find a way to have people discuss point without having to have someone watching the discussions...
