### ISSUE TITLE
Missing indicator of whether a point is good, bad, or neutral

### ISSUE THREAD

**Issue by hugoroy** [tosdr/phoenix#229]
When editing a point or viewing a point (e.g. https://phoenix.tosdr.org/points/18 ) there is no indication of the ranking of the point (e.g. the orange thumbs down 👎 ) and no possibility to change the status (e.g. from orange to "neutral" i.e. informative)

**Comment by piks3l** [comment]
I believe this is fixed in the current version since [v0.3.3.1-alpha](https://github.com/tosdr/phoenix/tree/v0.3.3.1-alpha)
