### ISSUE TITLE
[enh] Add one privacy_related point to all services of the List

### ISSUE THREAD

**Issue by piks3l** [tosdr/phoenix#233]

**Comment by michielbdejong** [comment]
@piks3l will work on:
* [ ] youtube.com
* [ ] stackoverflow.com
* [ ] facebook.com
* [ ] reddit.com
* [ ] amazon.com
* [ ] google.com
* [ ] twitter.com
* [ ] github.com
* [ ] imdb.com
* [ ] quora.com
* [ ] instagram.com
* [ ] linkedin.com
* [ ] wikihow.com
* [ ] yelp.com
* [ ] pinterest.com
* [ ] tripadvisor.com
* [ ] theguardian.com
* [ ] nytimes.com
* [ ] walmart.com

I will work on:
* [ ] cnet.com
* [ ] foxnews.com
* [ ] yahoo.com
* [ ] cnn.com
* [ ] w3schools.com
* [ ] apple.com
* [ ] dictionary.com
* [ ] live.com
* [ ] bbc.com
* [ ] zillow.com
* [ ] goodreads.com
* [ ] urbandictionary.com
* [ ] etsy.com
* [ ] imgur.com
* [ ] wordpress.com
* [ ] blogspot.com
* [ ] microsoftonline.com
* [ ] blogger.com
* [ ] spotify.com
