### ISSUE TITLE
[fix] update status doesn't allow modification on the actual pointb

### ISSUE THREAD

**Issue by piks3l** [tosdr/phoenix#243]

**Comment by michielbdejong** [comment]
Also, how does 'update' relate to 'edit'? Maybe remove one of the two?

**Comment by madoleary** [comment]
is this in the works right now? if not i can take a look tonight.

**Comment by piks3l** [comment]
I think I fixed in the latest release https://github.com/tosdr/phoenix/releases/tag/v0.3-alpha

**Comment by piks3l** [comment]
Nope, not fixed yet. You can check it out. The general idea is that in use, the update point and edit point routine we thought about didn't really make sense. 

A curator would want to modify a point, it could be analysis for fixes, grade or status. Which should also be given a reason so the user knows what has been changed. And this changes should be show through the paper trail. It is recorded on the models but not well displayed on the views. I hope I make sense.

Right now, only the change of status needs a reason, curators can change details of the point with no reason, which isn't really good. 

Don't hesitate to contact me if you have any questions.

**Comment by madoleary** [comment]
Putting my pull request message here so we can continue discussing and maybe I can make further changes: I gave the point class its own 'reason' column in the points data table, so folks will have to run a db:migrate, if these updates are to be pulled. The idea is that a reason object is created when a point is updated by a curator, given the updated status and reason params on the point. Right now these reasons are only stored and not shown anywhere. There is something I don't understand with respect to the "versions" table. Why are we storing both versions and reasons? Does it make more sense to get rid of the reasons object and only track changes to the reason variable inside of points via versions? The purpose of the reasons object, however, was to encourage a type of dialog between the curators and the users. I don't see how this is being accomplished with how versions are currently tracked.

**Comment by piks3l** [comment]
Yes, the reasons part make sense as it is important to have a discussion between curators and users as we didn't implement a chat/forum functionality at first.

It did keep track of changes but only when modifying the status through the Update method. You could bypass this by using the Edit method and no tracking was made when you changed through this latest method. This is why we decided to implement better versioning: to keep track of any change made to a point or a service (also it was requested several times by different people). 

Now that we have versions implemented, they duplicated with reasons on keeping track of Update method changes but, on the contrary of versions, they allow messages to be left. 

Of course, we'd need to rationalize this. The fact we have both right now is only because we didn't had time to refactor this.

I'm going to take a look into #267 :)
