### ISSUE TITLE
find out about income tax / v.a.t. rules for people who work for our project

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#247]

**Comment by michielbdejong** [comment]
not directly a phoenix issue, but adding it here because i want to look into it during our next sprint.

**Comment by piks3l** [comment]
Apparently donations are exempt of VAT but we need an organisation to recieve it.

**Comment by michielbdejong** [comment]
ok! do we need one organization in each country, or can a single one be used for the whole EU?

**Comment by piks3l** [comment]
One in one country in the EU would work. maybe I could discuss with some ngo here in brussels

**Comment by piks3l** [comment]
I feel like we have this sorted right ? Will close tomorrow.

**Comment by michielbdejong** [comment]
👍
