### ISSUE TITLE
[bug] Delete point make a 500

### ISSUE THREAD

**Issue by piks3l** [tosdr/phoenix#262]
Need investigation

**Comment by madoleary** [comment]
This is working locally for me, which makes me think that something isn't compiling properly to Heroku. Found this thread: https://stackoverflow.com/questions/26697251/rails-apps-destroy-delete-method-is-not-working-on-heroku-but-works-in-local-ma

**Comment by piks3l** [comment]
Confirmed in the current local version as well. Investigating
