### ISSUE TITLE
[enh] Don't show services that don't have a rating on the home page ? 

### ISSUE THREAD

**Issue by piks3l** [tosdr/phoenix#266]

**Comment by madoleary** [comment]
What about services that have no points, too?

**Comment by piks3l** [comment]
Well, services with no rating, have no points as one is linked to the other ahaha

**Comment by madoleary** [comment]
Okay. I mean that could be contributing to how slowly edit is loading too. I can work on this.

**Comment by piks3l** [comment]
Great ! thanks !

**Comment by piks3l** [comment]
Fixed and merged : #273
