### ISSUE TITLE
order by rating button is not working on "all points" tab

### ISSUE THREAD

**Issue by madoleary** [tosdr/phoenix#274]
The order by rating button under the "all points" tab on the points index page is not working for me. It works fine for pending points. I can look into this. I also think it would be a good idea, visually, to have the search bar and the order by rating button on the same line with space between.

**Comment by madoleary** [comment]
upon further investigation, the order by rating button under the "pending points" tab is sorting all points, not just pending points, so when you click the button, the page replenishes with all points sorted by rating, and not just pending points. under the "all points" tab, the button is still not working.

**Comment by madoleary** [comment]
Another strange thing seems to be happening here: If you navigate to the "pending points" tab on the points index page and click the "order by rating" button, it returns multiple instances of the same pending points. For example, while on the "pending points" tab, control+F for "[Good] Reddit allows users to leave the service," and you get one result BEFORE clicking the "order by rating" button. AFTER clicking the button, you get three results.

**Comment by piks3l** [comment]
That might me because of duplicates in the database, which isn't surprising. There have been few of those from the import. Cleaned some but it isn't done yet :)

**Comment by madoleary** [comment]
That could be a problem in other places, but it's doing the same thing on my local machine with my local data. I found the problem last night after console-logging the lines of the javascript. The script, regardless of whether it's on the "pending" tab or on the "all" tab, is grabbing all of the points in the erb file. So when on the "pending" tab, it grabs the pending points that are already there, as well as "all" of the points, so it grabs the pending points twice, plus the rest of the points, and thus reorders all of them by rating, with the pending points grabbed and re-rendered multiple times. The script works fine if you take away the tab functionality, so I think it's more a problem with page design and how the elements are compartmentalized , as the script is getting confused by the elements it's interacting with. I can work this out this week, but it might involve making a separate page for pending points.

**Comment by piks3l** [comment]
Oh ok, good job there !

> it might involve making a separate page for pending points.

I don't mind, anything to make the UX/UI clearer :)

**Comment by madoleary** [comment]
fixed this -- see pull request #280
