### ISSUE TITLE
UI: don't use justified text

### ISSUE THREAD

**Issue by hugoroy** [tosdr/phoenix#276]
![image](https://user-images.githubusercontent.com/1629771/38311242-02384a08-381f-11e8-8ac7-d9124f608aa4.png)

**Comment by piks3l** [comment]
Where does that come from ?

**Comment by hugoroy** [comment]
↪ Christopher Talib / 2018-04-05, 00:43 (CEST):
> Where does that come from ? 


From edit.tosdr.org, another example attached.

**Comment by piks3l** [comment]
Aw damn, gonna take a look a it
