### ISSUE TITLE
what is the rank col in the Point table ? 

### ISSUE THREAD

**Issue by piks3l** [tosdr/phoenix#279]
@madoleary and @michielbdejong  any idea where does that come from ? Is it from the idea we had about make a classification of the best points during the first sprint ? 

In case, it's this, do anyone object we remove that (through a migration of course)

**Comment by madoleary** [comment]
i think yeah, we were going to implement some type of ranking system where people could vote on the most popular points. might play to the gamification idea, but not a priority.

**Comment by piks3l** [comment]
ok great, let's leave it there then
