### ISSUE TITLE
Unauthorized to add point 

### ISSUE THREAD

**Issue by pavsh** [tosdr/phoenix#320]
Hi,
I'm a new user at Tos and tried to contribute by pressing "add point".
I get the "unauthorized.." message.

**Comment by piks3l** [comment]
Hey, wait two minutes for deployment and it should be good ! Thanks for raising the issue and happy contribution :grin:

**Comment by pavsh** [comment]
O.k thank you. I'll update you about the result.

**Comment by piks3l** [comment]
Thanks !

**Comment by pavsh** [comment]
Working!!
