### ISSUE TITLE
missing logos

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#338]
<img width="562" alt="screen shot 2018-05-14 at 15 42 25" src="https://user-images.githubusercontent.com/408412/40000999-85a53684-578d-11e8-82d8-1f75e471e4db.png">

**Comment by michielbdejong** [comment]
In the long term we should have a logo field in the services table in phoenix, but for now we can also just add these directly to https://github.com/tosdr/tosdr-build/tree/master/src/logo

**Comment by piks3l** [comment]
Is this error log from Phoenix ?

**Comment by michielbdejong** [comment]
No, this is on the actual https://tosdr.org/

**Comment by michielbdejong** [comment]
fixed
