### ISSUE TITLE
Keep an eye on the database row count

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#343]
The database DATABASE_URL on Heroku app edit-tosdr-org is approaching its allocated storage capacity.

The database contains 7,956 rows. The Hobby-dev plan allows a maximum of 10,000 rows. If the databases exceeds 10,000 rows then INSERT privileges will be revoked, preventing more data from being written. INSERT privileges are automatically reinstated if rows are removed and the database once again complies with the plan limit.

To avoid a disruption to your service, migrate the database to a Basic ($9/month) or higher plan:

https://devcenter.heroku.com/articles/upgrade-heroku-postgres-with-pgbackups

If you are unable to upgrade the database, you should limit or reduce the number of records in it.

**Comment by piks3l** [comment]
Generally speaking, the website is still slow even after increasing the amount of dyns and refactoring the n+1 calls to the DB. I don't understand why, but maybe it would be necessary to move out of Heroku to something cheaper but with more scalability ?

**Comment by michielbdejong** [comment]
You're right, loading https://edit.tosdr.org takes 23 to 25 seconds. But loading https://edit.tosdr.org/services/new and https://edit.tosdr.org/services and https://edit.tosdr.org/points only takes 0.5 seconds.

So we should just make https://edit.tosdr.org/points the home page then, right?

**Comment by piks3l** [comment]
I'm looking into performance for rails. I'll try to work something by compressing the most of our assets and other things. I'm working on that today and tomorrow. I think it's one of the main things we should look into right now. People won't go to the app if it's slow.

**Comment by michielbdejong** [comment]
@piks3l would you be willing to consider making https://edit.tosdr.org/points instead of https://edit.tosdr.org/ the landing page? Because it's only the home page that is causing problems, and that does not contain any information that's not already on https://tosdr.org itself, right?

**Comment by michielbdejong** [comment]
or maybe we can just show a call to action, with a few options?

**Comment by piks3l** [comment]
https://edit.tosdr.org/points isn't made to be a landing page, it is just a list of points, I think it's going to be very confusing UX-wise. 

The landing page of Phoenix has cards and users can already check for existing services or not entirely rated services. It would be redundant with the info displayed on https://tosdr.org only if we have a direct link between the two app, which isn't the case yet (unless i'm mistaken). 

Anyway, I ran Phoenix on https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fedit.tosdr.org&tab=desktop and the results are really worrying, especially on this level of the app. If we increase the database, the load and the amount of users, it just can't get better.

I'll keep you updated.

**Comment by michielbdejong** [comment]
Thanks!

I updated the postgres addon to hobby:basic, so for the time being, we'll be paying 25$ for the dyno and 9$ for the db at Heroku.

**Comment by piks3l** [comment]
See #258 for the discussing about perfomance
