### ISSUE TITLE
Can services get an A with the current rating system?

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#375]
Looking at https://github.com/tosdr/phoenix/blob/master/app/models/service.rb#L40-L49 a services needs an average point rating of at least 8.5 to get an A. But the highest rating a point can get through https://github.com/tosdr/phoenix/blob/master/app/views/points/_full_form.html.erb#L27 is a 'Good', which has rating 8.

So 'Good' points move a service's rating towards B, 'Neutral' points move it towards 'C', and 'Bad' and 'Blocker' points both move it towards 'F'. A 'D' means somewhere inbetween neutral and bad.

**Comment by Vinnl** [comment]
Fixed by #378.
