### ISSUE TITLE
Contributors should be allowed to add a service?

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#387]

**Comment by michielbdejong** [comment]
Would you be ok with that, @piks3l?

**Comment by michielbdejong** [comment]
also, adding a case.

**Comment by piks3l** [comment]
> Contributors should be allowed to add a service?

Yes ! We locked this for the work before the release of the Beta because we didn't want to break too much the db. But definitly

> also, adding a case.

I'm less convinced about this one. I think it's more for the curator realm, but I guess it's okay anyway

**Comment by Vinnl** [comment]
This was fixed by #391 right?
