### ISSUE TITLE
Don't allow curators to destroy services (and cases?)

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#388]
If a service has been reviewed, we may want to make it invisible on the site (for instance, if the service no longer exists, or was merged into another service as a duplicate), and we can update the details of a service, but I think we shouldn't erase history. Setting to invisible is better than destroying, i think.

I'm not quite sure if the same logic should apply to cases; if no points use a case, and we don't want to use it, then maybe it's ok to remove a case from the database, in favor of other cases, or while specifying a reason like 'this case is out of scope'.

**Comment by piks3l** [comment]
Deleting Services is now impossible (I don't remember from which version). Deleting cases is impossible if there are points liked to it.
