### ISSUE TITLE
can't input custom title/analysis when creating a point from a case

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#396]
I wanted to create 'easy to read' for visible.com, and specify that it's because they use "folding paragraphs" in https://www.visible.com/legal/privacy.html which i thought was quite neat.

I wasn't able to specify anything except for the case and the source, and then once the point had been created, i couldn't find how to edit it.

**Comment by Vinnl** [comment]
I think this works now, right? If not, please re-open.
