### ISSUE TITLE
Imported neutral case has a rating of 10

### ISSUE THREAD

**Issue by Vinnl** [tosdr/phoenix#423]
In [`cases.json`](https://github.com/tosdr/phoenix/blob/master/old_db/cases.json), the case "personal data is used for advertising" has a neutral rating. However, [on edit.tosdr.org](https://edit.tosdr.org/cases/216/edit), its rating is 10, whereas it should be 5.

/cc @michielbdejong

**Comment by michielbdejong** [comment]
"name":"personal data is used for advertising","point":"neutral","score":10,"topic":"track"}`

so classification 'neutral',  weight 10 (not 5) is correct.
