### ISSUE TITLE
Imported points do not link to the original Google Groups discussion

### ISSUE THREAD

**Issue by Vinnl** [tosdr/phoenix#453]
For example, [this point](https://edit.tosdr.org/points/1460) links to edit.tosdr.org/points/Imported as a source. That's an invalid link. It would be nice if it would link to the original discussion from which we could presumably find out the actual source, and hence verify the claims made.

**Comment by michielbdejong** [comment]
That point was probably imported from the Meteor tool. For instance https://edit.tosdr.org/points/2240 was imported from the mailing list, and does have the source link correctly.

**Comment by michielbdejong** [comment]
I think there's not much else we can do with this? Please reopen if this is still an issue.
