### ISSUE TITLE
How to handle services that don't seem to exist anymore?

### ISSUE THREAD

**Issue by madoleary** [tosdr/phoenix#464]
Just wondering what to do in this case, from a curation perspective. Delete the service? Mark all points as declined? I'm partial to the latter. For example, Players Crate. Can't seem to find it online, unless I'm missing something...

**Comment by Vinnl** [comment]
I would mark them as declined indeed - if you add a note that the service no longer exists, it's all traceable. (Perhaps Players Crate is the pcrate service? The URL mentioned, pcrate.com, is no longer online.)

**Comment by michielbdejong** [comment]
maybe we can add a field to mark the service as shut down? that seems cleaner than marking each point individually as declined.

In any case, this was a bigger problem a year ago, see https://github.com/tosdr/tosdr-build/issues/60

I updated tosdr.org to order services by Alexa rating, so if the url of a service is down, it will be all the way at the bottom. Also, through the browser extension, these urls will not be reachable either :)
