### ISSUE TITLE
Figure out how to deal with annotations on old versions of Terms

### ISSUE THREAD

**Issue by Vinnl** [tosdr/phoenix#470]
Use case: [Facebook has had one point annotated](https://edit.tosdr.org/services/182/annotate). However, the annotation was made on an old version of the terms of service. A solution should take into account:

- that we don't want to lose all annotations every time the terms are updated
- that points can get outdated when terms change
- that the text that has been annotated for one version of the terms might have moved to a different location in a new version

**Comment by michielbdejong** [comment]
this now happens after a crawl.
