### ISSUE TITLE
Annotate view should fetch terms from the `crawl_reviewed` dir from TosBack for services that are located there

### ISSUE THREAD

**Issue by Vinnl** [tosdr/phoenix#471]

**Comment by Vinnl** [comment]
@JimmStout What is the reason for the distinction between `crawl` and `crawl_reviewed` in ToSBack? Facebook is located in both, but the one in `crawl` is very outdated, and e.g. ResearchGate is only in the `crawl` folder.

**Comment by michielbdejong** [comment]
Done, but see also https://github.com/tosdr/tosback2/issues/40
