### ISSUE TITLE
Add link to service in the Point page

### ISSUE THREAD

**Issue by Dostoi** [tosdr/phoenix#511]
When you're on a point page, you can't easily go to the service page. It would be great to change the service name to be a link to the service page.

For example, in this page, DuckDuckGo would be a link to its page :
https://edit.tosdr.org/points/588

**Comment by Vinnl** [comment]
@Dostoi It is now, thanks for the feedback! Let us know if you have further suggestions :)

**Comment by Dostoi** [comment]
No problem, you're welcome. Thanks you for your work :)
