### ISSUE TITLE
Export to api version 2

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#523]
For example, on https://tosdr.org/api/2/service/wordpress-com.json you would get something like:
```js
{
  alexa: 56,
  domains: [ 'wordpress.com' ],
  name: 'WordPress.com',
  logo: '/logo/wordpress-com.png',
  wikipedia: 'https://en.wikipedia.org/wiki/WordPress.com',
  twitter: '@wordpressdotcom',
  docs: {
    'Terms of Service': {
      topRev: '8754c42a94047cf2ab20e44eb0972adb6d259848',
      url: 'http://en.wordpress.com/tos/',
      xPath: '//div[@class=\'pagebody\']',
      points: [
        {
          quoteStart: 345,
          quoteEnd: 6578,
          * quoteText: 'You hereby grant an irrevocable, non-transferable license to your data.',
          caseId: 123,
          * caseTitle: 'Irrevocable, non-transferable license',
          * caseClassification: 'bad',
          * caseWeight: 30
        }
      ]
    }
  },
  * class: 'B'
}

**Comment by Vinnl** [comment]
Some thoughts off the top of my head:

- What are the `*` in there?
- Could this benefit from adding a service ID as well?
- Where does the Alexa rating come from btw? Is it up-to-date? Wouldn't it be better to let clients look those up themselves?
- Would `logo` be better as a full URL including hostname?
- Maybe we want to add a key identifying ToS's and privacy policy's specifically? Other documents could of course still be added, but it could be useful to explicitly identify these two documents that many services have in common?
- Maybe this is the point at which we might also want/have to think about multiple services with the same docs.
- Might be a good idea to rename `topRev` to something that identifies that as relating to ToSback, e.g. `tosback_commit` or something.
- Is `xPath` needed? It might be better to use ToSback as the canonical source of that.
- Do we want to include the case in here, or should we refer to a separate case ID? It might be nice if you could query the API to get a list of all docs to which a certain case applies.
- Keys in JSON need to be quoted as well, and strings are quoted inside double quotes ;)

**Comment by Vinnl** [comment]
@michielbdejong I saw some commits in tosdr-build referencing an API v2. Do we have answers to the above questions? (/decided which are irrelevant?)

**Comment by michielbdejong** [comment]
no, i just added a new endpoint that browser extensions can use, without doing a full data model overhaul. This is probably not necessary at this time, I think.

**Comment by michielbdejong** [comment]
closing for now.
