### ISSUE TITLE
Services with only pending points are shown as being rated A

### ISSUE THREAD

**Issue by Vinnl** [tosdr/phoenix#534]
They should show N/A.

**Comment by michielbdejong** [comment]
What about services with only 1 approved point? Should this somehow depend on the 'comprehensive' flag?

**Comment by Vinnl** [comment]
I think once points are approved it's good to show what the rating would be once it's marked as complete? (Though then again, maybe we don't want a point's effect on the complete rating to influence the classification of that point.)

**Comment by michielbdejong** [comment]
ok, then i think it makes sense to display a service rating if and only if that service has at least one approved point.

**Comment by Vinnl** [comment]
I think so too; I'll pick this up.

**Comment by piks3l** [comment]
Isn't that fixed in #546  ? (and wrongly referenced #543 )
