### ISSUE TITLE
Services with approved points still show a Rating N/A

### ISSUE THREAD

**Issue by Vinnl** [tosdr/phoenix#554]
For example, Tapas has [several approved points](https://edit.tosdr.org/services/586), yet is being [listed](https://edit.tosdr.org/services) as N/A.

**Comment by michielbdejong** [comment]
It's because none of the cases have a classification.

**Comment by michielbdejong** [comment]
Updated them to neutral / bad / bad / neutral, respectively, guided by the values from `gh:tosdr/tosdr-build/scripts/cases.js`.

Hm, but rating is still 'N/A' on https://edit.tosdr.org/services?query=tapas

**Comment by piks3l** [comment]
I think I pinpoined the error in the Service.rb model ` if (num_blocker + num_bad + num_good + counts['neutral'])` cf my revision in the closed PR. I can take care of that today/tomorrow. I have some time and mood to :)
