### ISSUE TITLE
Recent changes cards layout flickers when hovered

### ISSUE THREAD

**Issue by davidak** [tosdr/phoenix#559]
Steps to reproduce:

1. open https://edit.tosdr.org/
1. move cursor to bottom border of a Recent changes card
1. the card starts flickering

See video: https://youtu.be/DBsiB-Kb5WI (other flickering due to screen recording software)

---

Reproducible in Chromium 65.0.3325.162 and Firefox 61.0 (only while moving cursor). Not tested other browsers.
NixOS 18.03.132803.2f06e04b74e (GNU/Linux)

**Comment by Vinnl** [comment]
Wow, that is jarring. I now removed the hover effect altogether, as it implies an interactivity that is not there. Hope that fixes it for you.

**Comment by davidak** [comment]
@Vinnl yes, thank you.
