### ISSUE TITLE
[enh] Fixing some view in the Case views

### ISSUE THREAD

**Issue by piks3l** [tosdr/phoenix#566]
* [X] Show view of a case doesn't say it list points (and I got confused)
* [X] #462 
* [X] The search bar in the Case index doesn't return consistent data

**Comment by Vinnl** [comment]
I assume this is fixed in #567?

(Tip: If you say `Fixes #566` instead of `See #566`, GitHub will automatically close this issue when the PR is merged.)

**Comment by Youngblood1978** [comment]
Im trying everything i can to remove 404 495 500 and 505 errors

**Comment by Youngblood1978** [comment]
Ill uninstall reinstall if thats what it takes or backup data and remove to a factory reset would be simplified I just like knowing i have everything backed up before doing this as last resort
