### ISSUE TITLE
[bug] NoMethodError in Services#show

### ISSUE THREAD

**Issue by piks3l** [tosdr/phoenix#574]
error: undefined method `empty?' for nil:NilClass
url: services/331?scope=archived-versions

**Comment by michielbdejong** [comment]
I think archived versions are now shown at the bottom anyway, so I think we can remove the archived-versions scope.

**Comment by piks3l** [comment]
Ok then, because it will render a 500 on production if we keep it.

**Comment by Vinnl** [comment]
I presume this is fixed by #575 then?
