### ISSUE TITLE
When editing a case, the 'weight' form field defaults to 50, even if the weight was set to a different number

### ISSUE THREAD

**Issue by madoleary** [tosdr/phoenix#578]
For example, if you try to edit a case that displays a weight of 90, the form field defaults to 50, which means you have to change it back to 90 before you submit any edits, if you're able to spot the discrepancy. This is a risk, as it is not completely obvious and changes the weight of a case, if you don't notice it.

**Comment by piks3l** [comment]
it is in the line 7 of `views/cases/_form.html.erb`

`        <%= f.input :score, collection: 0..100, selected: 50, label: 'Weight', hint: "Range: 0..100. Higher weight make good points extra good, and bad/blocker points extra bad. Higher weight points have more impact on a service's rating, and are also displayed more prominently in the review summaries on https://tosdr.org." %>
`

the selected: 50 must be the reason, blame it on me, it was in #567

**Comment by madoleary** [comment]
Ah ok! No problem. I can take care of it if you want.

**Comment by piks3l** [comment]
Yeah sure, I'm stuck on other things right now ahah. Thanks !

**Comment by Vinnl** [comment]
Oh haha, I noticed this myself before I saw this issue, and fixed it in #579.
