### ISSUE TITLE
TODO: add advanced validation for import points

### ISSUE THREAD

**Issue by piks3l** [tosdr/phoenix#59]
The current import: 
* import topics - 100%
* import services - 90% (for some reasons some services are not validated)
* import points : works but need to find a way to allow validation by binding services and topics through the JSON in order to keep previous work.

Current status: too tired to think of something. Will do that hopefully before midday.

**Comment by piks3l** [comment]
Import of points take far more time than what is needed. The database has different generation of JSON plus spams and invalid values. 

Topics have been imported to production and Services will be added manually for the alpha release presentation to ensure consistency in the presentation. The old database is present on the server in /old_db so if people feel like getting their hands dirty, could be nice. Otherwise, #wontfix for the alpha.

**Comment by michielbdejong** [comment]
This is fixed now, points, services, and topics are all imported successfully by `rails db:create db:migrate db:seed`.
