### ISSUE TITLE
order comments by created_at

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#644]
See https://edit.tosdr.org/points/4474 the comment appear in random order

**Comment by Vinnl** [comment]
Did you solve this already @michielbdejong? They appear in chronological order for me, I think?

![image](https://user-images.githubusercontent.com/4251/44456422-bf084080-a600-11e8-8912-9fb6495cf4e0.png)

**Comment by michielbdejong** [comment]
But the second one is the oldest one, right?

**Comment by michielbdejong** [comment]
08:48 > 08:40

**Comment by Vinnl** [comment]
Ehm, I knew I was blind. Disregard my comment :P
