### ISSUE TITLE
selection panic

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#645]
When trying to quote `<li> Changes or Discontinuance of the Service. We …ver on account of any change to the Service.</li>` on https://edit.tosdr.org/services/524/annotate?point_id=4266 I'm getting a client-side panic.

Investigating.

**Comment by michielbdejong** [comment]
```sh
document.getElementsByClassName('documentContent')[3].innerText.substring(8144, 8439)
"<li> Changes or Discontinuance of the Service. We reserve the right to modify or discontinue the Service at any time (including by limiting or discontinuing certain features of the Service) without notice to you. We will have no liability whatsoever on account of any change to the Service.</li>"
```

**Comment by michielbdejong** [comment]
Conclusion: [`sanitize`](https://github.com/tosdr/phoenix/blob/master/app/helpers/application_helper.rb#L32) treats unrecognized HTML tags like `<u>` differently (it removes them), and probably also adds tags like `</li></ul>` at the end if they are missing. So workaround for this bug is to remove the hideTags helper.

**Comment by Vinnl** [comment]
I've now added a proper fix: only do the sanitisation after making sure that crawled tags are not parsed as tags but rendered as text enclosed in `<` and `>`. See https://github.com/tosdr/phoenix/pull/647
