### ISSUE TITLE
Qwant quotes are off-by-one

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#655]
See for instance https://edit.tosdr.org/points/4277 and https://edit.tosdr.org/points/4277

I'm pretty sure I did select the first 'Q' with my browser while setting those quotes.

**Comment by Vinnl** [comment]
Fantastic... `doc.length` in Javascript: 11893. `doc.length` in Ruby: 11892. This'll be fun.

**Comment by Vinnl** [comment]
I'm going to wager a guess right now that this little guy in the Privacy Policy is the culprit: `🙂`.
