### ISSUE TITLE
Assign a case to all approved points

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#657]
select count(*) from points where "case_id"=235 and "status"='approved'; count 
-------
   161

Of those, 155 also have no quote, and of those, 92 are owned by user 4.

**Comment by michielbdejong** [comment]
81 of those are owned by user_id 4, will try to get rid of those today.

**Comment by michielbdejong** [comment]
```sql
select count(*) from points where case_id=235 and status='approved';
 count 
-------
     0
(1 row)
```

\o/

**Comment by Vinnl** [comment]
Great job Michiel!
