### ISSUE TITLE
duplicates in service points listing

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#665]
I guess this is because it now selects a random subset of points https://edit.tosdr.org/services/270

**Comment by Vinnl** [comment]
What do you mean by "it now selects a random subset of points"? I don't see any recent code changes in the points table code, other than the added capability of viewing pending points on the service view?

**Comment by michielbdejong** [comment]
ah, found out what was going on; if you hover over the eye icons, you see the list of points is correct, it's just displaying the case titles instead of the point titles, and there are some duplications there for Dropbox
