### ISSUE TITLE
I can't add a point

### ISSUE THREAD

**Issue by WalterKlosse** [tosdr/phoenix#667]
When I want to add a point to newly added service email.cz with case and title The service will not allow third parties to access your personal information without a legal basis it won't let me and it just says

can't be blank
Write your analysis and comments

under the Analysis section, but I already wrote analysis.

**Comment by Vinnl** [comment]
Oops, sorry, that's my fault! Will be fixed in a minute.

**Comment by Vinnl** [comment]
The fix should now be live @WalterKlosse, apologies for the inconvenience.
