### ISSUE TITLE
When adding a comment to a point with changes requested, add a (checked by default) checkbox that marks it back as pending

### ISSUE THREAD

**Issue by Vinnl** [tosdr/phoenix#674]
Or some other way that allows the author of a point to indicate that they've processed the change.

**Comment by michielbdejong** [comment]
if you actually changes something, it will set the status to pending, unless you select 'draft'.
you can also comment and then separately set the status from changes-requested to pending, or to draft.

your use case is when the author wants to say 'no' to the requested changes, right? hopefully that's not a default flow? :)

**Comment by michielbdejong** [comment]
ah, right. Yes, that's an odd one out - adding the excerpt can be done from the show view, without going through the edit view. It is also the only edit that can be done by others than the author of the point. For consistency, only the author should be able to change the linked excerpt, and also the point should always go (back) to pending (or to draft) when the author updates the excerpt.

Another thought, partially related, was that like we now show 'Points for you to review' on the
https://edit.tosdr.org/ home page when logged in as a curator, we should also show a list of 'my points', especially highlighting the ones with 'changes-requested' status.
