### ISSUE TITLE
Stimulate adding documents rather than points

### ISSUE THREAD

**Issue by Vinnl** [tosdr/phoenix#675]
Right now, when looking at a service's overview page, there's a button below the list of points that encourages you to add a point.

I think it's about time we switch the preferred flow to annotating documents. In other words: the link should be to adding a document when there are none yet, and to the annotate view if there are. To allow for points to be created that are not linked to a specific quote, we can add a button at the bottom of the annotate view.

That will also allow us to get rid of the annotate button at the top of the service's page, which currently has the same visual priority as the new point button - a clear visual hierarchy is better UX :)

**Comment by michielbdejong** [comment]
i think my changes from this morning already achieve part of this? https://edit.tosdr.org/services/331 shows the Annotate button much more prominently (above the fold) than the add point button, right?

But yes, your proposed changes probably still make sense.
