### ISSUE TITLE
restrict options for status in point edit view

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#677]
when editing a point (as a curator), i see all possible statuses in the dropdown, and 'approved' (the current status) is pre-selected. Then, editing fails silently because i did not pick one of [pending, draft]. Instead, it should offer pending preselected, and draft as the only other option.

**Comment by madoleary** [comment]
I don't see this problem anymore. I don't remember on which form it took place -- the review form or the edit content form?

**Comment by michielbdejong** [comment]
Ah sorry, #717, #710 were duplicates of this older issue, in any case, it was fixed in #724.
