### ISSUE TITLE
client-side panic while annotating

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/phoenix#684]
Trying to select "A representative, non-exhaustive list of the types of automatically collected information may include: network or Internet protocol address and type of browser you are using (e.g., Chrome, Safari, Firefox, Internet Explorer), the type of operating system you are using, (e.g., Microsoft Windows or Mac OS), the name of your Internet service provider (e.g., Comcast, Verizon or AT&T) and domains used by such providers, mobile network, device identifiers (such as an Apple IDFA or an Android Advertising ID), device settings, browser settings, the web pages of the Services you have visited, Services visited before and after you visit a Service, the type of handheld or mobile device used to view the Service (e.g., iOS, Android), location information, and the content and advertisements you have accessed, seen, forwarded and/or clicked on." for https://edit.tosdr.org/services/318/annotate?point_id=1133

**Comment by Vinnl** [comment]
The panic occurs when you select this passage until `AT&T`, and does not occur when selecting until `AT&`.

**Comment by Vinnl** [comment]
Second observation: the document content in the data attribute lists the ampersand as `&amp;`, whereas  `document.getSelection()` of course just says `&`. Thus, the answer probably lies in normalising special characters in the data attribute. Now to find a way to properly do that for all special HTML entities in Ruby.

**Comment by Vinnl** [comment]
Hmm, no wait, it's the other way around - we want HTML entities to be rendered as such if they are present as such in the original document, as otherwise we either wouldn't be able to find them, or would have to unescape them every time we try to look them up, both in Ruby as on the client-side. (And also, it's probably not a good idea to unescape data in an HTML attribute, as it will break out of the attribute.)

**Comment by michielbdejong** [comment]
happening again now, when trying to annotate "IF YOU DO NOT WANT TO CONTINUE TO BE CHARGED ON A RECURRING MONTHLY BASIS, YOU MUST CANCEL THE APPLICABLE PAID SUBSCRIPTION THROUGH YOUR SPOTIFY ACCOUNT’S SUBSCRIPTION PAGE OR TERMINATE YOUR SPOTIFY ACCOUNT BEFORE THE END OF THE RECURRING MONTHLY PERIOD. PAID SUBSCRIPTIONS CANNOT BE TERMINATED BEFORE THE END OF THE PERIOD FOR WHICH YOU HAVE ALREADY PAID, AND EXCEPT AS EXPRESSLY PROVIDED IN THESE TERMS, SPOTIFY WILL NOT REFUND ANY FEES THAT YOU HAVE ALREADY PAID. THE LIMITATION SECTION SETS FORTH ADDITIONAL TERMS REGARDING CANCELLATION OF YOUR PAID SUBSCRIPTION.&lt;/p&gt;" on IF YOU DO NOT WANT TO CONTINUE TO BE CHARGED ON A RECURRING MONTHLY BASIS, YOU MUST CANCEL THE APPLICABLE PAID SUBSCRIPTION THROUGH YOUR SPOTIFY ACCOUNT’S SUBSCRIPTION PAGE OR TERMINATE YOUR SPOTIFY ACCOUNT BEFORE THE END OF THE RECURRING MONTHLY PERIOD. PAID SUBSCRIPTIONS CANNOT BE TERMINATED BEFORE THE END OF THE PERIOD FOR WHICH YOU HAVE ALREADY PAID, AND EXCEPT AS EXPRESSLY PROVIDED IN THESE TERMS, SPOTIFY WILL NOT REFUND ANY FEES THAT YOU HAVE ALREADY PAID. THE LIMITATION SECTION SETS FORTH ADDITIONAL TERMS REGARDING CANCELLATION OF YOUR PAID SUBSCRIPTION.&lt;/p&gt;" on https://edit.tosdr.org/services/225/annotate?point_id=905

**Comment by michielbdejong** [comment]
hm, never mind, it seems to have worked now when I retried it.

**Comment by michielbdejong** [comment]
ok, there is a problem though: when you select that paragraph up to the final `.` and then press shift-right, it will (invisibly) select the `</p>` which you see pasted there. If that's included in the selection, annotation fails. Hitting shift-left a few times, removing those invisible characters from the end of the quote, eventually you can annotate. it's ok for me because i know this now, but not very usable for other reviewers.

**Comment by michielbdejong** [comment]
it seems to be harder to select longer quotes now than earlier today. @Vinnl did you change anything there that may be causing this?

**Comment by michielbdejong** [comment]
For instance, try to annotate " we may be required by law to store the information we collect, even after you have terminated your use of the eBuddy Services.&lt;/p&gt; &lt;p&gt;For technical reasons, it may be impossible for us to determine whether you have stopped using the eBuddy Services. For the mobile applications, it may also be impossible for eBuddy to determine whether you have deleted the application" on https://edit.tosdr.org/services/305/annotate

**Comment by michielbdejong** [comment]
I'm pretty sure annotating multiple paragraphs was possible in the past; I'll try to git-bisect the issue locally.

**Comment by michielbdejong** [comment]
It broke somewhere between edfdb90 and f1d8df1

**Comment by Vinnl** [comment]
Yeah, there's a multi-paragraph selection that was already annotated. Changing the excerpt, and then changing it back to the same multi-paragraph selection indeed led to the error again. It's almost guaranteed to be 86e9ab86fef5f7b4fd681c9a92b4333af0c93a1b, as that's the only change related to the annotation view I believe.

**Comment by michielbdejong** [comment]
yes, i just bisected it and ended up at that commit.

**Comment by Vinnl** [comment]
Ah, found the culprit. Kinda dumb: I replaced special characters with their literal HTML entities, but I did that _after_ inserting my own special characters inside the hidden tag. Switching over the order of the substitutions fixes it. Sorry!

**Comment by michielbdejong** [comment]
it's a pity that it will re-introduce the AT&T problem, but that's a smaller problem than the current situation

**Comment by Vinnl** [comment]
It should fix both :)

**Comment by michielbdejong** [comment]
ah, nice! so we can have both AT&T and multi-paragraph working? that would be awesome :)

**Comment by Vinnl** [comment]
Fix deployed, please confirm whether it works for you :)
