### ISSUE TITLE
`all.json` includes services with a space in their key

### ISSUE THREAD

**Issue by Vinnl** [tosdr/phoenix#687]
In [`all.json`](https://tosdr.org/api/1/all.json), there are keys like `tosdr/review/ bookogs.com` (i.e. with a space before the domain). I'm not sure whether that's due to erroneous spaces inserted for those services in Phoenix, but it's probably a good idea to trim the domains anyway.

**Comment by Vinnl** [comment]
@michielbdejong Could you give a pointer as to what script is responsible for generating `all.json`? I can't find it...

**Comment by michielbdejong** [comment]
It's because there are spaces in the comma-separated 'domains' field of https://edit.tosdr.org/services/603.

I also found spaces in domains for services 326, 611, 615, 620, fixed those too. I'll add a `trim` step to https://github.com/tosdr/phoenix/blob/master/db/export_services_to_old_db.rb#L39
