### ISSUE TITLE
case 198: reword to sound more neutral?

### ISSUE THREAD

**Issue by madoleary** [tosdr/phoenix#711]
https://edit.tosdr.org/cases/198

Right now it reads as if it's negative, whereas I don't think translation of terms and privacy statements into several languages is necessarily negative. Plus, the classification and weight are both neutral, so the language of the case itself should reflect that.

**Comment by madoleary** [comment]
(I can take care of this if folks agree)

**Comment by Vinnl** [comment]
Sounds good to me.

**Comment by madoleary** [comment]
Done!
