### ISSUE TITLE
Handling points for "sony": PlayStation?

### ISSUE THREAD

**Issue by madoleary** [tosdr/phoenix#716]
Most of the relevant privacy statements and terms online for the Sony service are for PlayStation. Okay to use those where needed for points under the Sony service? Don't want to be misleading.

**Comment by michielbdejong** [comment]
https://www.playstation.com/en-gb/legal/privacy-policy/ is what you are subject to when you create a PlayStation Network account. So then we should rename the services 'Sony' to 'PlayStation Network' (that is the name of the service you use). That also avoids clashing with e.g. Sony Mobile https://www.sonymobile.com/global-en/legal/privacy/

**Comment by michielbdejong** [comment]
Done.
