### ISSUE TITLE
Deleting documents fails

### ISSUE THREAD

**Issue by Photon-GitHub** [tosdr/phoenix#718]
If you want to delete documents, e.g. the duplicates on this page
https://edit.tosdr.org/services/252/annotate

you will receive a "Uh-Oh! It looks like you're lost" error.

**Comment by Vinnl** [comment]
So ehm... Apparently we just hadn't implemented this yet. It should work now, and I've tested it with one of the duplicates, but I'd appreciate if you could try whether it works for you as well :)

**Comment by Photon-GitHub** [comment]
It does work now, but I noticed a little typo: In recent changes a document deletion is called e.g. „destroyd Document 539“

**Comment by Vinnl** [comment]
Haha yes, I noticed that too. Unfortunately, that's not something I typed manually, but Ruby on Rails (the programming framework we use) trying to do some magic to turn a word into past tense, and failing. @piks3l or @madoleary (or perhaps @michielbdejong), do you know whether we can override Rails simply appending a `-d` to a word like "Destroy" to turn it into the past tense in the list of recent changes?

**Comment by Vinnl** [comment]
Ah, I'd have sworn it'd be something Rails would do :)
