### ISSUE TITLE
dang ky w88

### ISSUE THREAD

**Issue by titandn** [tosdr/phoenix#738]
https://w88-yes.com

**Comment by Vinnl** [comment]
Hi @titandn, unfortunately, we can only communicate on English here. If you wish to add a service to tosdr.org, you can contribute it yourself at edit.tosdr.org.

**Comment by titandn** [comment]
Mong admin add website https://w88-yes.com tosdr system, I do not have, now my web class B + now to the system tosdr, thank you many

**Comment by Vinnl** [comment]
@titandn [I see](https://edit.tosdr.org/services/751). Add a link to the terms of service and other legal documents using the "Add a document for review" button. Then, you can click the "Review documents" button to review them.

However, the review will have to be approved. Thus, if the terms are not in English, unfortunately we are currently unable to do that review. We will be looking at adding support for additional languages in the future, but until then, unfortunately it is not possible to include reviews for languages that none of the reviewers speak.
